### ISSUE TITLE
FileNotFoundError when starting run

### ISSUE THREAD

**Issue by tzdwi** [ExcaliburZero/megyr#16]
Hi there! I'm starting to experiment with `megyr` and having a fun time so far. That said, I occasionally get a `FileNotFoundError` when I start a run, with no changes made after a successful run. It seems to be looking for a profiles.index file before it gets created. 

My inlist.mustache file is:
```
&star_job

  ! begin with a pre-main sequence model
    create_pre_main_sequence_model = .true.

/ !end of star_job namelist


&controls

  ! starting specifications
    initial_mass = {{initial_mass}} ! in Msun units
    initial_z = 6d-3 ! metallicity
    initial_y = 259d-3 ! He abundance, Y=0.25 + 1.5Z (Eldridge et al. 2017)

  ! Stop after 50 Myr
    max_age = 50000000
  
  ! Post Main Sequence stuff
  ! use C/O enhanced opacities
  ! important for He-burning onwards
    use_Type2_opacities = .true.
    Zbase = 0.006

  ! configure mass loss on RGB & AGB
    cool_wind_RGB_scheme = 'Dutch'
    cool_wind_AGB_scheme = 'Dutch'
    RGB_to_AGB_wind_switch = 1d-4
    Dutch_scaling_factor = 0.8 

  ! Hot winds
    hot_wind_scheme = 'Vink'
/ ! end of controls namelist
```

The python script I'm running looks like

```python
import megyr
import numpy as np

def run_megyr():
    megyr.run({
        "input": {
            "mesa_configs": ["inlist.mustache"]
        },
        "output": {
            "mesa_profile_summary_file": "mesa_profile_attributes.csv"
        },
        "stages": {
            "mesa_params": {
                "initial_mass": [20,21,22,23,24,25,26,27,28,29,30]
            }
        }
    })
    
if __name__ == '__main__':
    run_megyr()
```

and the traceback looks like

```python
MESA: {'initial_mass': 20}
Already completed MESA
Traceback (most recent call last):
  File "run_megyr.py", line 19, in <module>
    run_megyr()
  File "run_megyr.py", line 13, in run_megyr
    "initial_mass": [20,21,22,23,24,25,26,27,28,29,30]
  File "/Users/carina/anaconda3/lib/python3.7/site-packages/megyr/__init__.py", line 54, in run
    mesa_data = load_or_collect_mesa_data(config, output_dir, mesa_dir_name, logs_dir_name)
  File "/Users/carina/anaconda3/lib/python3.7/site-packages/megyr/__init__.py", line 127, in load_or_collect_mesa_data
    rows = mesa.get_mesa_data(config, output_dir, mesa_dir_name, logs_dir_name)
  File "/Users/carina/anaconda3/lib/python3.7/site-packages/megyr/mesa.py", line 80, in get_mesa_data
    num_profiles = profile.read_num_profiles(profile_index)
  File "/Users/carina/anaconda3/lib/python3.7/site-packages/megyr/profile.py", line 6, in read_num_profiles
    with open(filepath, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './out/mesa_initial_mass_20__/LOGS/profiles.index'
```

I've double and triple checked to make sure I've deleted the `out` directory, and am still running into this bug. Thanks!

**Comment by tzdwi** [comment]
Ah I can temporarily fix this by moving all of my code out of the working directory, deleting everything, and starting a new working directory. Not ideal, certainly, but a workaround.

**Comment by tzdwi** [comment]
I think I got it! Even after deleting the `out` directory, I still needed to delete `completed_tasks.csv`. If this is the desired behavior, feel free to close the issue (though it may be worth noting on the [getting started page](https://megyr.readthedocs.io/en/latest/getting-started.html))

**Comment by ExcaliburZero** [comment]
I think this is intended behavior. I think it was implemented to base "completion" on the `completed_tasks.csv` file. That file serves as the indicator of which tasks have been completed.

The reason for this was so that you can run it incrementally and new runs will pickup where the last left off (sort-of), and it allow you to re-run everything by just deleting that one file.

You are right that this should be documented somewhere. In fact it would probably be useful to have a specific error message in the program that informs the user of this instead of just giving them an unhelpful `FIleNotFoundError`.

**Comment by tzdwi** [comment]
Gotcha, thank you!!
